version: '3'
services:
  backend:
    build: ./backend/
    image: desafiovolldb
    volumes:
      - "./backend:/app"
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    image: desafiovoll
    volumes:
      - "./frontend:/app"
    ports:
      - 3000:3000
    depends_on:
      - backend